export enum WebSocketAction {
  CONNECT_TAB = 'connectTab',
  CONNECT_WINDOW = 'connectWindow',
  AI = 'ai',
  CALLBACK_AI_STEP = 'aiCallbackStep',
  AGENT = 'agent',
  AI_SCRIPT = 'aiScript',
  CALLBACK = 'callback',
  ERROR = 'error',
  DOWNLOAD_VIDEO = 'downloadVideo',
  DOWNLOAD_VIDEO_CALLBACK = 'downloadVideoCallback',
  SITE_SCRIPT = 'siteScript',
  COMMAND = 'command',
  TEST = 'test',
}
